stages:
    - lint
    - test
    - history_copy
    - generate_report
    - report

lint:
    stage: lint
    image: python:3.8-slim
    tags:
      - docker
    before_script:
      - python -m pip install -U pip && python -m pip install pylint==2.12.2
    script:
      - python -m pylint $(echo -n /app/*.py && echo -n ' ' && find /app -type d -maxdepth 1 -exec test -e '{}'/__init__.py \; -print | grep -v '^/app/\.')

run_tests:
    stage: test
    services:
      - selenium/standalone-chrome
    image: python:3.9
    tags:
      - docker
    before_script:
        - pip install -r requirements.txt
        - apt-get update
        - apt-get install libnss3
    script:
        - pytest -v --alluredir=./allure_results tests/
    allow_failure: true
    artifacts:
      when: always
      paths:
        - ./allure_results
      expire_in: 1 month

history_copy:
    stage: history_copy
    image: python:3.9
    artifacts:
        when: always
        paths:
            - ./allure_results
        expire_in: 1 month
    script:
        - 'curl --location --output artifacts.zip "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=pages&job_token=$CI_JOB_TOKEN"'
        - unzip artifacts.zip
        - chmod -R 777 public
        - cp ./public/history/* ./allure_results

generate_report:
  stage: generate_report
  image: frankescobar/allure-docker-service
  script:
     - allure generate -c allure_results -o allure-report
  artifacts:
    paths:
      - ./allure-results
      - ./allure-report
    expire_in: 1 month
  rules:
    - when: always

pages:
  stage: report
  script:
    - mkdir public
    - cp -r ./allure-report/* public
  artifacts:
    paths:
      - public
    expire_in: never
  needs:
    - job: generate_report
